"""Initial MetroVerify v2 production schema

Revision ID: 656a1dd7845a
Revises: 
Create Date: 2026-10-02 14:34:08.528359

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '656a1dd7845a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('previous_event_hash', sa.String(length=64), nullable=True),
    sa.Column('event_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_id'), 'audit_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('fee_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee_schedule_code', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.String(length=100), nullable=False),
    sa.Column('accuracy_class', sa.String(length=50), nullable=True),
    sa.Column('min_capacity', sa.Float(), nullable=False),
    sa.Column('max_capacity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('base_fee', sa.Float(), nullable=False),
    sa.Column('additional_fee_rule', sa.String(length=255), nullable=True),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('source_notification', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_rules_fee_schedule_code'), 'fee_rules', ['fee_schedule_code'], unique=False)
    op.create_index(op.f('ix_fee_rules_id'), 'fee_rules', ['id'], unique=False)
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('office_name', sa.String(length=200), nullable=False),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisdictions_code'), 'jurisdictions', ['code'], unique=True)
    op.create_index(op.f('ix_jurisdictions_district'), 'jurisdictions', ['district'], unique=False)
    op.create_index(op.f('ix_jurisdictions_division'), 'jurisdictions', ['division'], unique=False)
    op.create_index(op.f('ix_jurisdictions_id'), 'jurisdictions', ['id'], unique=False)
    op.create_table('mpe_bands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruleset_code', sa.String(length=100), nullable=False),
    sa.Column('accuracy_class', sa.String(length=50), nullable=False),
    sa.Column('verification_mode', sa.String(length=50), nullable=False),
    sa.Column('lower_interval_limit', sa.Float(), nullable=False),
    sa.Column('upper_interval_limit', sa.Float(), nullable=True),
    sa.Column('mpe_factor_e', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpe_bands_id'), 'mpe_bands', ['id'], unique=False)
    op.create_index(op.f('ix_mpe_bands_ruleset_code'), 'mpe_bands', ['ruleset_code'], unique=False)
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('officer_in_charge', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offices_code'), 'offices', ['code'], unique=True)
    op.create_index(op.f('ix_offices_id'), 'offices', ['id'], unique=False)
    op.create_table('rulesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_document', sa.String(length=255), nullable=False),
    sa.Column('section_reference', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rulesets_code'), 'rulesets', ['code'], unique=True)
    op.create_index(op.f('ix_rulesets_id'), 'rulesets', ['id'], unique=False)
    op.create_table('standard_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standard_asset_id', sa.String(length=100), nullable=False),
    sa.Column('asset_tag', sa.String(length=100), nullable=False),
    sa.Column('nominal_mass', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('accuracy_class', sa.String(length=20), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('calibration_date', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('laboratory', sa.String(length=255), nullable=False),
    sa.Column('traceability_reference', sa.String(length=255), nullable=False),
    sa.Column('hierarchy_level', sa.Enum('INTERNATIONAL_REFERENCE', 'NATIONAL_STANDARD', 'REGIONAL_STANDARD', 'SECONDARY_STANDARD', 'WORKING_STANDARD', name='standardhierarchyenum'), nullable=False),
    sa.Column('current_location', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'QUARANTINED', 'IN_CALIBRATION', 'RETIRED', name='assetstatusenum'), nullable=False),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standard_assets_asset_tag'), 'standard_assets', ['asset_tag'], unique=True)
    op.create_index(op.f('ix_standard_assets_id'), 'standard_assets', ['id'], unique=False)
    op.create_index(op.f('ix_standard_assets_standard_asset_id'), 'standard_assets', ['standard_asset_id'], unique=True)
    op.create_table('test_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('instrument_type', sa.String(length=100), nullable=False),
    sa.Column('accuracy_class', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('steps_config', sa.Text(), nullable=False),
    sa.Column('source_rule_reference', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_templates_id'), 'test_templates', ['id'], unique=False)
    op.create_index(op.f('ix_test_templates_template_code'), 'test_templates', ['template_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('APPLICANT', 'INSPECTOR', 'SUPERVISOR', 'ADMIN', 'PUBLIC_VERIFIER', name='roleenum'), nullable=False),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('verification_interval_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('instrument_category', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.String(length=100), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_until', sa.DateTime(), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_interval_rules_id'), 'verification_interval_rules', ['id'], unique=False)
    op.create_index(op.f('ix_verification_interval_rules_rule_code'), 'verification_interval_rules', ['rule_code'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.String(length=100), nullable=False),
    sa.Column('instrument_type', sa.String(length=100), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('model_approval_number', sa.String(length=100), nullable=True),
    sa.Column('accuracy_class', sa.Enum('CLASS_I', 'CLASS_II', 'CLASS_III', 'CLASS_IIII', name='accuracyclassenum'), nullable=False),
    sa.Column('max_capacity', sa.Float(), nullable=False),
    sa.Column('min_capacity', sa.Float(), nullable=False),
    sa.Column('verification_scale_interval_e', sa.Float(), nullable=False),
    sa.Column('actual_scale_interval_d', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('installation_location', sa.Text(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('division', sa.String(length=100), nullable=False),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNVERIFIED', 'PENDING_VERIFICATION', 'VERIFIED', 'EXPIRED', 'SUSPENDED', 'REQUIRES_REVERIFICATION', 'REJECTED', name='instrumentstatusenum'), nullable=False),
    sa.Column('last_verification_date', sa.DateTime(), nullable=True),
    sa.Column('next_due_date', sa.DateTime(), nullable=True),
    sa.Column('previous_certificate_id', sa.String(length=100), nullable=True),
    sa.Column('seal_configuration', sa.Text(), nullable=True),
    sa.Column('verification_mark_location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instruments_district'), 'instruments', ['district'], unique=False)
    op.create_index(op.f('ix_instruments_division'), 'instruments', ['division'], unique=False)
    op.create_index(op.f('ix_instruments_id'), 'instruments', ['id'], unique=False)
    op.create_index(op.f('ix_instruments_instrument_id'), 'instruments', ['instrument_id'], unique=True)
    op.create_index(op.f('ix_instruments_serial_number'), 'instruments', ['serial_number'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.String(length=100), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('application_type', sa.Enum('NEW_VERIFICATION', 'RE_VERIFICATION', 'PREMISES_VERIFICATION', name='applicationtypeenum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'QUERY_RAISED', 'QUERY_RESPONDED', 'APPROVED', 'REJECTED', 'SCHEDULED', 'UNDER_INSPECTION', 'INSPECTION_PASSED', 'INSPECTION_FAILED', 'CERTIFICATE_PENDING', 'CERTIFICATE_ISSUED', 'ACTIVE', 'EXPIRED', 'SUSPENDED', 'REQUIRES_REVERIFICATION', 'CANCELLED', name='applicationstatusenum'), nullable=False),
    sa.Column('is_premises_verification', sa.Boolean(), nullable=True),
    sa.Column('advance_notice_days', sa.Integer(), nullable=True),
    sa.Column('jurisdiction_id', sa.Integer(), nullable=True),
    sa.Column('jurisdiction_status', sa.Enum('VALID_JURISDICTION', 'WRONG_JURISDICTION', 'REFERRED', 'REJECTED', name='jurisdictionstatusenum'), nullable=False),
    sa.Column('jurisdiction_notes', sa.Text(), nullable=True),
    sa.Column('assigned_inspector_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.String(length=50), nullable=True),
    sa.Column('scheduled_time', sa.String(length=50), nullable=True),
    sa.Column('test_centre_or_premises', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['jurisdiction_id'], ['jurisdictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_application_id'), 'applications', ['application_id'], unique=True)
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('application_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('PURCHASE_BILL', 'MODEL_APPROVAL_CERTIFICATE', 'AUDIT_REPORT', 'NOC', 'PREVIOUS_CERTIFICATE', 'GRAS_CHALLAN', 'OTHER', name='documenttypeenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('MISSING', 'UPLOADED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'NOT_APPLICABLE', name='documentstatusenum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_documents_document_id'), 'application_documents', ['document_id'], unique=True)
    op.create_index(op.f('ix_application_documents_id'), 'application_documents', ['id'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('ruleset_version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('visual_inspection_status', sa.String(length=50), nullable=True),
    sa.Column('zero_test_status', sa.String(length=50), nullable=True),
    sa.Column('indication_test_status', sa.String(length=50), nullable=True),
    sa.Column('repeatability_test_status', sa.String(length=50), nullable=True),
    sa.Column('eccentricity_test_status', sa.String(length=50), nullable=True),
    sa.Column('discrimination_test_status', sa.String(length=50), nullable=True),
    sa.Column('tare_test_status', sa.String(length=50), nullable=True),
    sa.Column('zero_return_status', sa.String(length=50), nullable=True),
    sa.Column('high_capacity_substitution_status', sa.String(length=50), nullable=True),
    sa.Column('final_result', sa.String(length=50), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=True),
    sa.Column('ambient_temperature_c', sa.Float(), nullable=True),
    sa.Column('relative_humidity_pct', sa.Float(), nullable=True),
    sa.Column('barometric_pressure_hpa', sa.Float(), nullable=True),
    sa.Column('test_location', sa.String(length=255), nullable=True),
    sa.Column('standard_asset_ids', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['test_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_id'), 'inspections', ['id'], unique=False)
    op.create_index(op.f('ix_inspections_inspection_id'), 'inspections', ['inspection_id'], unique=True)
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('challan_number', sa.String(length=100), nullable=False),
    sa.Column('gras_grn', sa.String(length=100), nullable=True),
    sa.Column('scroll_number', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=False),
    sa.Column('fee_breakdown', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(length=150), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_records_id'), 'payment_records', ['id'], unique=False)
    op.create_index(op.f('ix_payment_records_payment_id'), 'payment_records', ['payment_id'], unique=True)
    op.create_table('query_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('raised_by', sa.String(length=150), nullable=False),
    sa.Column('raised_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_records_id'), 'query_records', ['id'], unique=False)
    op.create_index(op.f('ix_query_records_query_id'), 'query_records', ['query_id'], unique=True)
    op.create_table('inspection_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=True),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=100), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('captured_by', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_evidences_id'), 'inspection_evidences', ['id'], unique=False)
    op.create_table('inspection_test_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_input_json', sa.Text(), nullable=True),
    sa.Column('computed_result_json', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspection_test_steps_id'), 'inspection_test_steps', ['id'], unique=False)
    op.create_table('seal_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('seal_number', sa.String(length=100), nullable=False),
    sa.Column('seal_type', sa.String(length=100), nullable=False),
    sa.Column('seal_location', sa.String(length=255), nullable=False),
    sa.Column('verification_mark_location', sa.String(length=255), nullable=False),
    sa.Column('applied_by', sa.String(length=150), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('condition', sa.String(length=100), nullable=False),
    sa.Column('tamper_status', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seal_records_id'), 'seal_records', ['id'], unique=False)
    op.create_table('test_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('step_key', sa.String(length=100), nullable=False),
    sa.Column('load_target', sa.Float(), nullable=False),
    sa.Column('standard_value', sa.Float(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=False),
    sa.Column('error', sa.Float(), nullable=False),
    sa.Column('error_percentage', sa.Float(), nullable=False),
    sa.Column('verification_interval_count', sa.Float(), nullable=False),
    sa.Column('mpe', sa.Float(), nullable=False),
    sa.Column('within_mpe', sa.Boolean(), nullable=False),
    sa.Column('run_index', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('corrected_by', sa.String(length=150), nullable=True),
    sa.Column('original_measurement_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_measurements_id'), 'test_measurements', ['id'], unique=False)
    op.create_table('verification_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.String(length=100), nullable=False),
    sa.Column('certificate_number', sa.String(length=100), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('verification_date', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('officer_name', sa.String(length=200), nullable=False),
    sa.Column('officer_designation', sa.String(length=150), nullable=False),
    sa.Column('office_name', sa.String(length=255), nullable=False),
    sa.Column('test_location', sa.String(length=255), nullable=False),
    sa.Column('fee_reference', sa.String(length=100), nullable=True),
    sa.Column('previous_certificate_number', sa.String(length=100), nullable=True),
    sa.Column('ruleset_version', sa.String(length=100), nullable=False),
    sa.Column('certificate_version', sa.String(length=50), nullable=False),
    sa.Column('qr_token', sa.String(length=255), nullable=False),
    sa.Column('certificate_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'ACTIVE', 'EXPIRING_SOON', 'EXPIRED', 'SUSPENDED', 'REVOKED', name='certificatestatusenum'), nullable=False),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('revoked_by', sa.String(length=150), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_certificates_certificate_id'), 'verification_certificates', ['certificate_id'], unique=True)
    op.create_index(op.f('ix_verification_certificates_certificate_number'), 'verification_certificates', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_verification_certificates_id'), 'verification_certificates', ['id'], unique=False)
    op.create_index(op.f('ix_verification_certificates_qr_token'), 'verification_certificates', ['qr_token'], unique=True)
    op.create_index(op.f('ix_verification_certificates_status'), 'verification_certificates', ['status'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_certificates_status'), table_name='verification_certificates')
    op.drop_index(op.f('ix_verification_certificates_qr_token'), table_name='verification_certificates')
    op.drop_index(op.f('ix_verification_certificates_id'), table_name='verification_certificates')
    op.drop_index(op.f('ix_verification_certificates_certificate_number'), table_name='verification_certificates')
    op.drop_index(op.f('ix_verification_certificates_certificate_id'), table_name='verification_certificates')
    op.drop_table('verification_certificates')
    op.drop_index(op.f('ix_test_measurements_id'), table_name='test_measurements')
    op.drop_table('test_measurements')
    op.drop_index(op.f('ix_seal_records_id'), table_name='seal_records')
    op.drop_table('seal_records')
    op.drop_index(op.f('ix_inspection_test_steps_id'), table_name='inspection_test_steps')
    op.drop_table('inspection_test_steps')
    op.drop_index(op.f('ix_inspection_evidences_id'), table_name='inspection_evidences')
    op.drop_table('inspection_evidences')
    op.drop_index(op.f('ix_query_records_query_id'), table_name='query_records')
    op.drop_index(op.f('ix_query_records_id'), table_name='query_records')
    op.drop_table('query_records')
    op.drop_index(op.f('ix_payment_records_payment_id'), table_name='payment_records')
    op.drop_index(op.f('ix_payment_records_id'), table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index(op.f('ix_inspections_inspection_id'), table_name='inspections')
    op.drop_index(op.f('ix_inspections_id'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_application_documents_id'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_document_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_instruments_serial_number'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_instrument_id'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_id'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_division'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_district'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_verification_interval_rules_rule_code'), table_name='verification_interval_rules')
    op.drop_index(op.f('ix_verification_interval_rules_id'), table_name='verification_interval_rules')
    op.drop_table('verification_interval_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_templates_template_code'), table_name='test_templates')
    op.drop_index(op.f('ix_test_templates_id'), table_name='test_templates')
    op.drop_table('test_templates')
    op.drop_index(op.f('ix_standard_assets_standard_asset_id'), table_name='standard_assets')
    op.drop_index(op.f('ix_standard_assets_id'), table_name='standard_assets')
    op.drop_index(op.f('ix_standard_assets_asset_tag'), table_name='standard_assets')
    op.drop_table('standard_assets')
    op.drop_index(op.f('ix_rulesets_id'), table_name='rulesets')
    op.drop_index(op.f('ix_rulesets_code'), table_name='rulesets')
    op.drop_table('rulesets')
    op.drop_index(op.f('ix_offices_id'), table_name='offices')
    op.drop_index(op.f('ix_offices_code'), table_name='offices')
    op.drop_table('offices')
    op.drop_index(op.f('ix_mpe_bands_ruleset_code'), table_name='mpe_bands')
    op.drop_index(op.f('ix_mpe_bands_id'), table_name='mpe_bands')
    op.drop_table('mpe_bands')
    op.drop_index(op.f('ix_jurisdictions_id'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_division'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_district'), table_name='jurisdictions')
    op.drop_index(op.f('ix_jurisdictions_code'), table_name='jurisdictions')
    op.drop_table('jurisdictions')
    op.drop_index(op.f('ix_fee_rules_id'), table_name='fee_rules')
    op.drop_index(op.f('ix_fee_rules_fee_schedule_code'), table_name='fee_rules')
    op.drop_table('fee_rules')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
